# NumPy 

NumPy (Numpy) is short for Numerical Python and is a Python library, created in 2005 by Travis Oliphant. 
It is a library considered to be the fundamental package for scientific computing with Python and very important in Data Science because almost all libraries in the PyData Ecosystem depend on NumPy as one of their main building blocks.
### What for?
NumPy has functions for working in domain of arrays, linear algebra, matrices. It is also offers an array object that processes over 40x faster than list operations.
### Why NumPy over Lists?
Numpy arrays are stored at continuous place in memory unlike lists(locality of reference), as a result they are faster and more efficeient than lists.
Numpy also has bindings to C libraries and is optimized to work wuith latest CPU architectures.
For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Numpy Installation 

**. With Conda**

If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:
    
    conda install numpy
    
**. Using pip**

If you do not have Anaconda , you can install via command line using pip:
    
    pip install numpy

**. Otherwise,**
please refer to Numpy's official documentation on [installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

## Using NumPy

After installation, NumPy can be imported as a library:

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [351]:
print(np.__version__)

1.18.5



# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (although they can have only one row or one column). Arrays are homogeneous objects.

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays
Arrays can be created in variouys ways, some of whicn we will cover below:

##### By directly converting a list or list of lists:

In [352]:
just_a_value = True #Try replacing with strings and even Booleans
just_a_value

True

In [353]:
np.array(just_a_value)#0-D array

array(True)

In [354]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [355]:
np.array(my_list)#1-D array(Vector)

array([1, 2, 3])

In [356]:
my_list_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_list_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [357]:
np.array(my_list_matrix)#2-D array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### By convering a tuple or tuple of tuples

In [358]:
my_tuple = (1,2,3)
my_tuple

(1, 2, 3)

In [359]:
np.array(my_tuple)#1-D array(Vector)

array([1, 2, 3])

In [360]:
my_tuple_matrix = ((1,2,3),(1,2,3))
my_tuple_matrix

((1, 2, 3), (1, 2, 3))

In [361]:
np.array(my_tuple_matrix)#2-D array(matrix)

array([[1, 2, 3],
       [1, 2, 3]])

##### More Dimensions?

In [362]:
# Create a 3-D array with two 2-D arrays
my_3D_array = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
my_3D_array

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [363]:
np.array(my_3D_matrix)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

##### Defining dimensions

In [364]:
my_5D_array = np.array([1,2,3,4], ndmin=5) #Creates an array with 5-Dimensions

##### To check the dimension of an array

In [5]:
# Check the dimensions of the arrays we've been using
import numpy as np
a = [[1 , 2 , 3 , 4 , 9 , 20], [2 , 3 ,5 , 9 ,6 , 8]]
a_np = np.array(a).ndim 
a_np
# b = np.array(my_list).ndim
# c = np.array(my_list_matrix).ndim 
# d = np.array(my_tuple_matrix).ndim 
# e = np.array(my_3D_array).ndim 
# f = np.array(my_5D_array).ndim

# print(a)
# print(b)
# print(c)
# print(d)
# print(e)
# print(f)

2

In [366]:
# More D's?, Try to create an array with 10-Dimensions

## Data Types
NumPy supports a much greater variety of numerical types than Python does. A few of the fixed-size aliases are available include: *np.bool_, np.float32, np.uint32,np.uint8 etc.*

Note that each built-in data-type has a unique character (the updated Numeric typecodes) that identifies it. **np.int32** can be written as **'i4'** while **np.float32** can be written as **'f4'**

More on these data types, and those not listed here, are explored in the Structured arrays section of [Numpy documentation.](https://numpy.org/doc/stable)

In [367]:
np.array([1,2,4,])

array([1, 2, 4])

### dtype parameter
The desired data-type for the array. If not given, then the type will be the minimum type required to hold the objects

In [368]:
np.array([1,2,4], dtype='f4')

array([1., 2., 4.], dtype=float32)

In [369]:
np.array([1,2,4], dtype=np.float32)

array([1., 2., 4.], dtype=float32)

In [370]:
np.array([-1,2,4], dtype='i4')#signed int

array([-1,  2,  4])

In [371]:
np.array([-1,2,4], dtype=np.uint32)#unsigned int

array([4294967295,          2,          4], dtype=uint32)

### dtype attribute

You can also grab the data type of the object in the array:

In [372]:
arr.dtype

dtype('int32')

### dtype method
Create a data type object.

In [373]:
np.dtype('f')

dtype('float32')

## Data type conversion

### astype method
Create a copy of the array, casts to a specified type

In [374]:
arr = np.array([3.142,2,3])
print(arr)
print(arr.dtype)

[3.142 2.    3.   ]
float64


In [375]:
k = arr.astype('int')#Converts to int
print(k)
print(k.dtype)

[3 2 3]
int32


In [376]:
k = arr.astype('f')#Converts to float
print(k)
print(k.dtype)

[3.142 2.    3.   ]
float32


## View vs Copy

### View
View of the original data, the view does not own the data and changes made to original would reflect here

In [377]:
arr = np.array([15,12,13])

In [378]:
view = arr.view()
view

array([15, 12, 13])

In [379]:
arr[0] = 11
print(arr)
print(view)

[11 12 13]
[11 12 13]


In [380]:
arr = np.array([15,12,13])
view[0] = 10
print(arr)
print(view)

[15 12 13]
[10 12 13]


### Copy
Copy of the original data into a new array; the copy owns its own data and changes made to the original will not affect it.

In [381]:
arr = np.array([15,12,13])

In [382]:
copy = arr.copy()
copy

array([15, 12, 13])

In [383]:
arr[0]= 11
print(arr)
print(copy)

[11 12 13]
[15 12 13]


## Numpy Methods

There are lots of built-in numpy methods for various tasks, some for creating arrays, some for operations on arrays

### arange

Return evenly spaced values within a given interval. Equivalent to the traditional range

In [384]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [385]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [386]:
np.zeros(3)

array([0., 0., 0.])

In [387]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [388]:
np.ones(3)

array([1., 1., 1.])

In [389]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [390]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [391]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [392]:
np.eye(2) #Creates a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [393]:
np.eye(4,4) #Creates a 4X4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [394]:
np.random.rand(2)

array([0.24739976, 0.35900488])

In [395]:
np.random.rand(5,5)

array([[0.67427518, 0.04302122, 0.69659616, 0.99930389, 0.66069173],
       [0.77061917, 0.5964422 , 0.84099461, 0.43529003, 0.75246497],
       [0.83377565, 0.05801972, 0.65446306, 0.62689969, 0.07421722],
       [0.93508811, 0.86313461, 0.95842055, 0.90338414, 0.57453597],
       [0.05855675, 0.89553406, 0.15767215, 0.0111557 , 0.54127019]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [396]:
np.random.randn(2)

array([-0.04178174,  1.47437066])

In [397]:
np.random.randn(5,5)

array([[ 1.17246664,  0.3464853 , -1.15258712, -0.21919253,  0.15860136],
       [-0.49063454, -0.68368489, -3.00664398,  1.02427451, -0.55162956],
       [-0.81578788, -0.51277617,  0.47072146,  0.31366005, -0.01165574],
       [ 0.00387467, -0.81828745,  0.84972238, -0.27085532,  0.42960159],
       [ 1.15264658,  0.49423511,  1.04180339, -0.210302  ,  1.22695266]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [398]:
np.random.randint(1,100)

39

In [399]:
np.random.randint(1,100,10)

array([68, 12, 51, 24, 91, 11, 22, 16, 88, 29])

## Axis
Axis a parameter that determines the reference of a statement(method);either a row or a column of an array
```
    axis = 0    ==>   elements of columns
```
```
    axis = 1    ==>   elements of rows
```
  


In [400]:
axis=1

## Array Attributes and Methods

Let's discuss some useful attributes and methods on the two arrays below:

In [401]:
arr = np.random.randint(0,40,16)#16 random integers between 0 and 50
arr

array([15, 16, 31, 18, 19, 17, 33,  0, 11,  6, 11, 20, 27, 21, 14, 35])

### size 
Number of elements in an array. Size is an attribute not a method
arr.size

### shape

Shape of an array is the number of elements in each dimension. Shape is also an attribute.

In [402]:
arr.shape #Vector

(16,)

### reshape

Add, remove or change number of dimensions; changing the shape of an array. Reshape is a method.

In [403]:
arr.reshape(4,4) # matrix of 4rows,4columns 4 X 4

array([[15, 16, 31, 18],
       [19, 17, 33,  0],
       [11,  6, 11, 20],
       [27, 21, 14, 35]])

In [404]:
arr.reshape(1,16) # matrix of 1row,16columns 1 X 16

array([[15, 16, 31, 18, 19, 17, 33,  0, 11,  6, 11, 20, 27, 21, 14, 35]])

In [405]:
arr.reshape(1,16).shape

(1, 16)

In [406]:
arr.reshape(16,1) # matrix of 16rows,1column 16 X 1

array([[15],
       [16],
       [31],
       [18],
       [19],
       [17],
       [33],
       [ 0],
       [11],
       [ 6],
       [11],
       [20],
       [27],
       [21],
       [14],
       [35]])

In [407]:
arr.reshape(16,-1) # matrix of 16rows,and system define columns 16 X n

array([[15],
       [16],
       [31],
       [18],
       [19],
       [17],
       [33],
       [ 0],
       [11],
       [ 6],
       [11],
       [20],
       [27],
       [21],
       [14],
       [35]])

In [408]:
arr.reshape(4,4).shape

(4, 4)

### flatten
Collapse the array into one dimension.

In [409]:
arr.flatten()

array([15, 16, 31, 18, 19, 17, 33,  0, 11,  6, 11, 20, 27, 21, 14, 35])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [410]:
arr

array([15, 16, 31, 18, 19, 17, 33,  0, 11,  6, 11, 20, 27, 21, 14, 35])

In [411]:
reshaped_arr = arr.reshape(4,4)
reshaped_arr

array([[15, 16, 31, 18],
       [19, 17, 33,  0],
       [11,  6, 11, 20],
       [27, 21, 14, 35]])

In [412]:
print(sum([22, 26, 39,  7]))
print(sum([15,  3, 26, 13]))
print(sum([14, 33, 26, 23]))
print(sum([18, 11, 28,  6]))

94
57
96
63


#### max
Return the maximum along a given axis.

In [413]:
arr.max() 

35

In [414]:
reshaped_arr.max(axis=0) #returns the maximum values across the columns

array([27, 21, 33, 35])

In [415]:
reshaped_arr.max(axis=1) #returns the max across the rows

array([31, 33, 20, 35])

#### min
Return the minimum along a given axis.

In [416]:
arr.min()#Return the minimum along a given axis.

0

In [417]:
reshaped_arr.min(axis=0) #returns the minimum values across the columns

array([11,  6, 11,  0])

In [418]:
reshaped_arr.min(axis=1) #returns the min across the rows

array([15,  0,  6, 14])

#### argmax and argmin

In [419]:
arr.argmax()#Return the index location of the maximum value.

15

In [420]:
reshaped_arr.argmax(axis=1)#Return the index location of the maximum values across rows.

array([2, 2, 3, 3], dtype=int64)

In [421]:
arr.argmin()#Return the index location of the maximum.

7

In [422]:
reshaped_arr.argmax(axis=0)#Return the index location of the minimum values across columns.

array([3, 3, 1, 3], dtype=int64)